version: '3'

services:
  wkhtmltopdf:
    image: wkhtmltopdf
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      HOST: '0.0.0.0'
      PORT: '3000'
      PUBLIC_DIR: public
      MY_HOST_SERVICE_URL: 
    volumes:
      - public:/tmp/wkhtmltopdf-nodejs-express/public
      - templates:/tmp/wkhtmltopdf-nodejs-express/templates
    ports:
      - 3000:3000
      - 9229:9229 # - node inspector for debugging

volumes:
  public:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tmp/wkhtmltopdf-nodejs-express/public
  templates:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tmp/wkhtmltopdf-nodejs-express/templates
